name: Build template archives

on:
  push:
    paths-ignore:
      - 'dist/**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc

      - name: Install pnpm and dependencies
        uses: apify/actions/pnpm-install@v1.5.0

      # TODO: Also replace links in manifest.json
      - name: Build template archives
        run: pnpm run build

      - name: Commit the updated template archives
        uses: apify/actions/signed-commit@v1.4.0
        with:
          message: 'chore: Update template archives [skip ci]'
          add: 'dist/* templates/*'
          github-token: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}
