name: Build template archives

on:
  push:
    paths-ignore:
      - 'dist/**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install pnpm and dependencies
        uses: apify/workflows/pnpm-install@v0.41.1

      # TODO: Also replace links in manifest.json
      - name: Build template archives
        run: pnpm run build

      - name: Commit the updated template archives
        uses: apify/actions/signed-commit@v1.1.2
        with:
          message: 'chore: Update template archives [skip ci]'
          add: 'dist/* templates/*'
          github-token: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}
