name: Test Agent AI templates

on:
  workflow_call:

jobs:
  test-agent-ai-templates:
    name: Test Agent AI templates
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
        node-version: [ 22 ]
        python-version: ['3.10', '3.11', '3.12', '3.13']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm install
        npm install -g apify-cli
        ./node_modules/.bin/playwright install chromium --with-deps

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Chrome and Chromedriver
      run: |
        npx @puppeteer/browsers install chrome
        npx @puppeteer/browsers install chromedriver

    - name: Test Agent AI templates
      run: npm run test-agent-ai-templates
      env:
        APIFY_TOKEN: ${{ secrets.APIFY_TEST_USER_API_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.APIFY_SERVICE_ACCOUNT_OPENAI_API_KEY }}
