name: Test LLM AI Node.js templates

on:
  workflow_call:

jobs:
  test-llm-ai-node-templates:
    name: Test LLM AI Node.js templates
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
        node-version: [22]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm install
        npm install -g apify-cli

    - name: Test LLM AI Node.js templates
      run: npm run test-llm-ai-node-templates
      env:
        APIFY_TOKEN: ${{ secrets.APIFY_TEST_USER_API_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.APIFY_SERVICE_ACCOUNT_OPENAI_API_KEY }}
