name: Test Docker Builds

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  find-and-test-dockerfiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Maximize available disk space
        run: |
            # Remove unnecessary pre-installed tools
            sudo rm -rf /usr/share/dotnet
            sudo rm -rf /usr/local/lib/android
            sudo rm -rf /opt/ghc
            sudo rm -rf /usr/lib/jvm  # Remove Java installations if unused
            sudo rm -rf /usr/local/share/powershell  # Remove PowerShell
            sudo rm -rf /usr/local/share/boost  # Remove Boost libraries
            sudo apt-get remove -y --purge '^dotnet-.*' '^llvm-.*' 'libmono.*' 'mono-.*' 'ghc-.*' || true
            sudo apt-get autoremove -y
            sudo apt-get clean
            # Remove .git directory from root after checkout
            sudo rm -rf .git
            # Aggressive Docker cleanup
            sudo docker system prune -a -f

      - name: Test Dockerfile builds
        shell: bash
        run: ./scripts/test_docker_builds.sh

      - name: Cleanup
        if: always()
        run: |
          docker image prune -f
