name: Test Docker Builds

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  find-and-test-dockerfiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Dockerfile builds
        run: |
          # Find all Dockerfiles in templates directory
          mapfile -t dockerfiles < <(find templates -name "Dockerfile" -type f)

          if [ ${#dockerfiles[@]} -eq 0 ]; then
            echo "No Dockerfiles found in templates directory"
            exit 1
          fi

          successful_builds=0
          failed_builds=0

          for dockerfile in "${dockerfiles[@]}"; do
            echo "Testing Dockerfile: $dockerfile"
            echo "--------------------------------"

            # Get the parent directory name (template name) and sanitize it
            template_dir=$(basename "$(dirname "$(dirname "$dockerfile")")")
            # Replace any invalid characters with hyphen and convert to lowercase
            tag_name="test-$(echo "$template_dir" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]-')"

            # Get the directory containing the Dockerfile
            build_dir=$(dirname "$dockerfile")

            # Build the Docker image
            if docker build -f "$dockerfile" "$build_dir" --tag "$tag_name" --progress=plain; then
              echo "✓ Successfully built $dockerfile"
              ((successful_builds++))
            else
              echo "✗ Failed to build $dockerfile"
              ((failed_builds++))
            fi
            echo "--------------------------------"
          done

          echo "Build Summary:"
          echo "Successful builds: $successful_builds"
          echo "Failed builds: $failed_builds"

          if [ $failed_builds -gt 0 ]; then
            echo "Some Dockerfile builds failed"
            exit 1
          else
            echo "All Dockerfiles built successfully!"
            exit 0
          fi

      - name: Cleanup
        if: always()
        run: |
          docker image prune -f
